In [1]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_parquet("../data/tm_raw/2026-08-03-polygons-prod.geoparquet")
df.shape
df.head()

,project_id,project_name,country,framework_key,short_name,cohort,polygon_data_submission,ready_for_baseline,total_hectares_restored_goal,trees_grown_goal,...,is_active,source,deleted_at,geom,project_phase,ttc,tree_count_by_year,restoration_by_strategy,restoration_by_land_use,restoration_by_eco_region
0,a1062d22-dea2-4bb1-a1ce-f42cdfa5bdfb,Gender Equality and Sustainability in Collecti...,IND,hbf,None,hbf,no-polygons-submitted,False,2000.0,20000.0,...,True,uploaded,NaT,"b""\x01\x03\x00\x00\x00\x01\x00\x00\x00A\x00\x0...",implementation,"[(2023, 28.0)]",None,"[(2025, {""tree-planting"":1.0358408505320686})]","[(2025, {""agroforest"":1.0358408505320686})]","[(2025, {""Eastern highlands moist deciduous fo..."
1,a1062d22-dea2-4bb1-a1ce-f42cdfa5bdfb,Gender Equality and Sustainability in Collecti...,IND,hbf,None,hbf,no-polygons-submitted,False,2000.0,20000.0,...,True,uploaded,NaT,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00A\x00\x0...,implementation,"[(2023, 11.0)]",None,"[(2025, {""tree-planting"":1.1236239197853286})]","[(2025, {""agroforest"":1.1236239197853286})]","[(2025, {""Eastern highlands moist deciduous fo..."
2,a1062d22-dea2-4bb1-a1ce-f42cdfa5bdfb,Gender Equality and Sustainability in Collecti...,IND,hbf,None,hbf,no-polygons-submitted,False,2000.0,20000.0,...,True,uploaded,NaT,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00A\x00\x0...,implementation,"[(2023, 55.0)]",None,"[(2025, {""tree-planting"":2.2664304177826424})]","[(2025, {""agroforest"":2.2664304177826424})]","[(2025, {""Eastern highlands moist deciduous fo..."
3,a1062d22-dea2-4bb1-a1ce-f42cdfa5bdfb,Gender Equality and Sustainability in Collecti...,IND,hbf,None,hbf,no-polygons-submitted,False,2000.0,20000.0,...,True,uploaded,NaT,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00A\x00\x0...,implementation,"[(2023, 3.0)]",None,"[(2025, {""tree-planting"":0.06879325680771833})]","[(2025, {""agroforest"":0.06879325680771833})]","[(2025, {""Eastern highlands moist deciduous fo..."
4,a1062d22-dea2-4bb1-a1ce-f42cdfa5bdfb,Gender Equality and Sustainability in Collecti...,IND,hbf,None,hbf,no-polygons-submitted,False,2000.0,20000.0,...,True,uploaded,NaT,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00A\x00\x0...,implementation,"[(2023, 26.0)]",None,"[(2025, {""tree-planting"":0.039407254522370226})]","[(2025, {""agroforest"":0.039407254522370226})]","[(2025, {""Eastern highlands moist deciduous fo..."

In [12]:
f = df[
    (df["framework_key"] == "terrafund-landscapes") &
    (df["ready_for_baseline"] == True)
]

n_projects = f["project_id"].nunique()
n_polygons = f["poly_uuid"].nunique() 

print(f"Total projects: {n_projects}")
print(f"Total polygons: {n_polygons}")

Total projects: 32
Total polygons: 12516

In [13]:
f.polygon_data_submission.value_counts()

polygon_data_submission
all-polygons-received           12421
polygons-partially-submitted       95
Name: count, dtype: int64

In [14]:
confirm = f[
    (f["polygon_data_submission"] == "polygons-partially-submitted")]

In [23]:
confirm

,project_id,project_name,country,framework_key,short_name,cohort,polygon_data_submission,ready_for_baseline,total_hectares_restored_goal,trees_grown_goal,...,is_active,source,deleted_at,geom,project_phase,ttc,tree_count_by_year,restoration_by_strategy,restoration_by_land_use,restoration_by_eco_region
3240,166192d1-d194-416d-abb7-132877462359,Burundi 2023:Preserve and restore Ecological i...,BDI,terrafund-landscapes,BUR_23_COH,terrafund-cohort-2,polygons-partially-submitted,True,350.0,162000.0,...,True,greenhouse,NaT,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00A\x00\x0...,implementation,"[(2023, 89.0)]",None,"[(2026, {""tree-planting"":0.0097755820751823})]","[(2026, {""agroforest"":0.0097755820751823})]",None
3241,166192d1-d194-416d-abb7-132877462359,Burundi 2023:Preserve and restore Ecological i...,BDI,terrafund-landscapes,BUR_23_COH,terrafund-cohort-2,polygons-partially-submitted,True,350.0,162000.0,...,True,greenhouse,NaT,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00A\x00\x0...,implementation,"[(2023, 15.0)]",None,"[(2026, {""tree-planting"":0.34823780716208})]","[(2026, {""agroforest"":0.34823780716208})]",None
3242,166192d1-d194-416d-abb7-132877462359,Burundi 2023:Preserve and restore Ecological i...,BDI,terrafund-landscapes,BUR_23_COH,terrafund-cohort-2,polygons-partially-submitted,True,350.0,162000.0,...,True,greenhouse,NaT,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00A\x00\x0...,implementation,"[(2023, 17.0)]",None,"[(2026, {""tree-planting"":1.1911268262779})]","[(2026, {""agroforest"":1.1911268262779})]",None
3243,166192d1-d194-416d-abb7-132877462359,Burundi 2023:Preserve and restore Ecological i...,BDI,terrafund-landscapes,BUR_23_COH,terrafund-cohort-2,polygons-partially-submitted,True,350.0,162000.0,...,True,greenhouse,NaT,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00A\x00\x0...,implementation,"[(2023, 16.0)]",None,"[(2026, {""tree-planting"":1.1911267556424})]","[(2026, {""agroforest"":1.1911267556424})]",None
3244,166192d1-d194-416d-abb7-132877462359,Burundi 2023:Preserve and restore Ecological i...,BDI,terrafund-landscapes,BUR_23_COH,terrafund-cohort-2,polygons-partially-submitted,True,350.0,162000.0,...,True,greenhouse,NaT,"b'\x01\x03\x00\x00\x00\x01\x00\x00\x00,\x00\x0...",implementation,"[(2023, 40.0)]",None,"[(2026, {""tree-planting"":2.528321874649})]","[(2026, {""agroforest"":2.528321874649})]",None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3684,166192d1-d194-416d-abb7-132877462359,Burundi 2023:Preserve and restore Ecological i...,BDI,terrafund-landscapes,BUR_23_COH,terrafund-cohort-2,polygons-partially-submitted,True,350.0,162000.0,...,True,greenhouse,NaT,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00.\x00\x0...,implementation,"[(2025, 8.0)]",None,None,None,None
3685,166192d1-d194-416d-abb7-132877462359,Burundi 2023:Preserve and restore Ecological i...,BDI,terrafund-landscapes,BUR_23_COH,terrafund-cohort-2,polygons-partially-submitted,True,350.0,162000.0,...,True,greenhouse,NaT,"b""\x01\x03\x00\x00\x00\x01\x00\x00\x00@\x00\x0...",implementation,"[(2025, 5.0)]",None,None,None,None
3686,166192d1-d194-416d-abb7-132877462359,Burundi 2023:Preserve and restore Ecological i...,BDI,terrafund-landscapes,BUR_23_COH,terrafund-cohort-2,polygons-partially-submitted,True,350.0,162000.0,...,True,terramatch,NaT,"b""\x01\x03\x00\x00\x00\x01\x00\x00\x00\x1d\x00...",implementation,"[(2025, 85.0)]",None,None,None,None
3687,166192d1-d194-416d-abb7-132877462359,Burundi 2023:Preserve and restore Ecological i...,BDI,terrafund-landscapes,BUR_23_COH,terrafund-cohort-2,polygons-partially-submitted,True,350.0,162000.0,...,True,greenhouse,NaT,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\x0f\x00...,implementation,"[(2023, 88.0)]",None,None,None,None
3688,166192d1-d194-416d-abb7-132877462359,Burundi 2023:Preserve and restore Ecological i...,BDI,terrafund-landscapes,BUR_23_COH,terrafund-cohort-2,polygons-partially-submitted,True,350.0,162000.0,...,True,terramatch,NaT,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00c\x00\x0...,implementation,"[(2024, 82.0)]",None,None,None,None

In [19]:
sorted(set(f["short_name"]))

['BUR_23_APROCUVI',
 'BUR_23_COH',
 'BUR_23_RB2000',
 'BUR_23_WDI',
 'DRC_23_CCAO',
 'DRC_23_IGH',
 'GHA_23_EAF',
 'GHA_23_GGV',
 'GHA_23_HMPOANO',
 'GHA_23_INEC',
 'GHA_23_MIF',
 'GHA_23_SAFI',
 'KEN_23_AAE',
 'KEN_23_COPICAD',
 'KEN_23_COSEO',
 'KEN_23_GBM',
 'KEN_23_ITF',
 'KEN_23_JICBO',
 'KEN_23_LOCCOG',
 'KEN_23_PARAN',
 'KEN_23_SESANA',
 'KEN_23_SKWT',
 'KEN_23_SOLIDARIDAD',
 'KEN_23_WWF',
 'RWA_23_AEE',
 'RWA_23_APEFA',
 'RWA_23_BIRDLIFE',
 'RWA_23_FESD',
 'RWA_23_OSEPCCA',
 'RWA_23_RDIS',
 'RWA_23_REDO',
 'RWA_23_WCI']

In [20]:
df.columns

Index(['project_id', 'project_name', 'country', 'framework_key', 'short_name',
       'cohort', 'polygon_data_submission', 'ready_for_baseline',
       'total_hectares_restored_goal', 'trees_grown_goal', 'site_name',
       'site_id', 'poly_name', 'poly_uuid', 'plantstart', 'practice',
       'target_sys', 'distr', 'calc_area', 'status', 'version_name',
       'is_active', 'source', 'deleted_at', 'geom', 'project_phase', 'ttc',
       'tree_count_by_year', 'restoration_by_strategy',
       'restoration_by_land_use', 'restoration_by_eco_region'],
      dtype='object')

In [ ]:
# Criteria for selection

# Strong Remote
# Within imagery budget
# No ordering complications